languages:
  PHP: true
exclude_paths:
  - 'test/Store/Plugin/FillStore.php'
  - 'test/Store/Plugin/FilterStore.php'
  - 'test/Store/Plugin/FlattenStore.php'
  - 'test/Store/Plugin/IntersectionStore.php'
  - 'test/Store/Plugin/MapStore.php'
  - 'test/Store/Plugin/MergeStore.php'